### ISSUE TITLE
Not in pub.dev repository

### ISSUE THREAD

**Issue by cyounghusband** [motivq/ndt7_flutter#1]
Can't add it to my project using flutter or dart, as doesn't seem to be registered on pub.dev

**Comment by cpendergraft98** [comment]
You can import it directly from from the GitHub repository by using a `git` dependency in your `pubspec.yaml` like this:

```
ndt7:
    git:
      url: https://github.com/motivq/ndt7_flutter
      ref: main
```
